Spriting:
- icons/**

Mapping:
  - _maps/**

documentation:
  - .github/**
  - README.md

Balance:
  - code/modules/jobs/job_types/roguetown/**
  - code/modules/clothing/rogueclothes/**
  - code/game/objects/items/rogueweapons/**
